CREATE DATABASE AIStudyHub;
GO

USE AIStudyHub;
GO

-- 1. USER table
CREATE TABLE [USER] (
    [Id] UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    [Username] NVARCHAR(255) NOT NULL,
    [PasswordHash] NVARCHAR(MAX) NOT NULL,
    [CreatedAt] DATETIME2 NOT NULL DEFAULT GETDATE()
);
GO

-- 2. SUBJECT table
CREATE TABLE [SUBJECT] (
    [Id] UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    [UserId] UNIQUEIDENTIFIER NOT NULL,
    [Name] NVARCHAR(255) NOT NULL,
    [CourseCode] NVARCHAR(50),
    [ColorHex] NVARCHAR(10),
    CONSTRAINT [FK_SUBJECT_USER] FOREIGN KEY ([UserId]) REFERENCES [USER]([Id]) ON DELETE CASCADE
);
GO

-- 3. DOCUMENT table
CREATE TABLE [DOCUMENT] (
    [Id] UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    [SubjectId] UNIQUEIDENTIFIER NOT NULL,
    [Title] NVARCHAR(255) NOT NULL,
    [FilePath] NVARCHAR(MAX) NOT NULL,
    [FileType] NVARCHAR(50),
    [UploadedAt] DATETIME2 NOT NULL DEFAULT GETDATE(),
    CONSTRAINT [FK_DOCUMENT_SUBJECT] FOREIGN KEY ([SubjectId]) REFERENCES [SUBJECT]([Id]) ON DELETE CASCADE
);
GO

-- 4. TASK table
CREATE TABLE [TASK] (
    [Id] UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    [SubjectId] UNIQUEIDENTIFIER NOT NULL,
    [Title] NVARCHAR(255) NOT NULL,
    [DueDate] DATETIME2,
    [Status] NVARCHAR(50) DEFAULT 'Todo', -- Todo, InProgress, Done
    [Type] NVARCHAR(50), -- Assignment, Exam, Review
    CONSTRAINT [FK_TASK_SUBJECT] FOREIGN KEY ([SubjectId]) REFERENCES [SUBJECT]([Id]) ON DELETE CASCADE
);
GO

-- 5. ANNOTATION table
CREATE TABLE [ANNOTATION] (
    [Id] UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    [DocumentId] UNIQUEIDENTIFIER NOT NULL,
    [PageNumber] INT NOT NULL,
    [PosX] FLOAT NOT NULL,
    [PosY] FLOAT NOT NULL,
    [Content] NVARCHAR(MAX),
    [Type] NVARCHAR(50), -- Highlight, Note
    CONSTRAINT [FK_ANNOTATION_DOCUMENT] FOREIGN KEY ([DocumentId]) REFERENCES [DOCUMENT]([Id]) ON DELETE CASCADE
);
GO

-- 6. FLASHCARD_DECK table
CREATE TABLE [FLASHCARD_DECK] (
    [Id] UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    [SubjectId] UNIQUEIDENTIFIER NOT NULL,
    [DocumentId] UNIQUEIDENTIFIER NULL,
    [Title] NVARCHAR(255) NOT NULL,
    CONSTRAINT [FK_FLASHCARD_DECK_SUBJECT] FOREIGN KEY ([SubjectId]) REFERENCES [SUBJECT]([Id]) ON DELETE CASCADE,
    CONSTRAINT [FK_FLASHCARD_DECK_DOCUMENT] FOREIGN KEY ([DocumentId]) REFERENCES [DOCUMENT]([Id]) -- Không dùng CASCADE để tránh chu trình (multiple cascade paths)
);
GO

-- 7. FLASHCARD table
CREATE TABLE [FLASHCARD] (
    [Id] UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    [DeckId] UNIQUEIDENTIFIER NOT NULL,
    [FrontText] NVARCHAR(MAX) NOT NULL,
    [BackText] NVARCHAR(MAX) NOT NULL,
    [NextReviewDate] DATETIME2,
    [RepetitionCount] INT DEFAULT 0,
    CONSTRAINT [FK_FLASHCARD_FLASHCARD_DECK] FOREIGN KEY ([DeckId]) REFERENCES [FLASHCARD_DECK]([Id]) ON DELETE CASCADE
);
GO

-- 8. CHAT_SESSION table
CREATE TABLE [CHAT_SESSION] (
    [Id] UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    [DocumentId] UNIQUEIDENTIFIER NULL,
    [Title] NVARCHAR(255) NOT NULL,
    [CreatedAt] DATETIME2 NOT NULL DEFAULT GETDATE(),
    CONSTRAINT [FK_CHAT_SESSION_DOCUMENT] FOREIGN KEY ([DocumentId]) REFERENCES [DOCUMENT]([Id]) ON DELETE SET NULL
);
GO

-- 9. CHAT_MESSAGE table
CREATE TABLE [CHAT_MESSAGE] (
    [Id] UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    [SessionId] UNIQUEIDENTIFIER NOT NULL,
    [Sender] NVARCHAR(50) NOT NULL, -- User or AI
    [Content] NVARCHAR(MAX) NOT NULL,
    [Timestamp] DATETIME2 NOT NULL DEFAULT GETDATE(),
    CONSTRAINT [FK_CHAT_MESSAGE_CHAT_SESSION] FOREIGN KEY ([SessionId]) REFERENCES [CHAT_SESSION]([Id]) ON DELETE CASCADE
);
GO

-- 10. TAG table
CREATE TABLE [TAG] (
    [Id] UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    [Name] NVARCHAR(100) NOT NULL UNIQUE
);
GO

-- 11. DOCUMENT_TAG table
CREATE TABLE [DOCUMENT_TAG] (
    [DocumentId] UNIQUEIDENTIFIER NOT NULL,
    [TagId] UNIQUEIDENTIFIER NOT NULL,
    PRIMARY KEY ([DocumentId], [TagId]),
    CONSTRAINT [FK_DOCUMENT_TAG_DOCUMENT] FOREIGN KEY ([DocumentId]) REFERENCES [DOCUMENT]([Id]) ON DELETE CASCADE,
    CONSTRAINT [FK_DOCUMENT_TAG_TAG] FOREIGN KEY ([TagId]) REFERENCES [TAG]([Id]) ON DELETE CASCADE
);
GO
